// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { expand } from 'dotenv-expand';
import { defineConfig } from 'prisma/config';

// This line manually resolves the ${VARIABLES} in your .env
expand({ parsed: process.env as Record<string, string> });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
